---

- name: nodejs | APT key
  tags:
    - apt
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: nodejs | repository
  tags:
    - apt
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_ver }} {{ ansible_distribution_release }} main"
    filename: nodejs
    update_cache: yes

- name: nodejs | apt pinning
  tags:
    - apt
  template:
    src: apt_prefs.j2
    dest: /etc/apt/preferences.d/60nodesource

- name: nodejs | package
  tags:
    - package
  package:
    name: nodejs

- name: nodejs | update npm
  tags:
    - package
  npm:
    name: npm
    global: yes
    state: latest

