---

- name: nodejs | uninstall package
  tags:
    - package
  package:
    name: npm
    state: absent

- name: nodejs | remove repository
  tags:
    - apt
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_ver }} {{ ansible_distribution_release }} main"
    filename: nodejs
    state: absent
