---

- name: nodejs | uninstall package
  tags:
    - package
  package:
    name: npm
    state: absent

- name: nodejs | remove config files
  tags:
  - apt
  file:
    path: "{{ item }}"
    state: absent
  loop:
  - /etc/apt/sources.list.d/nodejs.list
  - "{{ nodejs_keyring }}"
  - "{{ nodejs_apt_prefs }}"
