#! /usr/bin/env ansible-playbook
# Uninstall role
# Use '-l' option to specify hosts from which to uninstall
---
- name: template | uninstall
  hosts: all
  tasks:
  - include_role:
      name: template
      tasks_from: uninstall.yml
