#! /usr/bin/env ansible-playbook
# Uninstall role
# Run prior to removing host from inventory groups, so hostvars are accessible
---
- name: nodejs | uninstall
  hosts: all
  tasks:
  - include_role:
      name: nodejs
      tasks_from: uninstall.yml
